dist: trusty

language: java

jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "$SONAR_SECRET_KEY"


script:
  - ./gradlew clean test
  - sonar-scanner

after_success:
  - docker build -t speech4j/tenant-service .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/tenant-service