dist: trusty

language: java

jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: $SONAR_TOKEN

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean test
  - gradle sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY

after_success:
  - docker build -t speech4j/tenant-service .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/tenant-service