dist: trusty
#
#language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "speech4j"

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean test
  - ./gradlew sonarqube --stacktrace

after_success:
  - docker build -t speech4j/tenant-service .gt
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/tenant-service

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'