dist: trusty

language: java

jdk:
  - openjdk11

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "speech4j"
    token:
      secure: "7f5c5d29aac23e01619c81f2cea39b19a0082c1f"

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean test
  - ./gradlew sonarqube

after_success:
  - docker build -t speech4j/tenant-service .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/tenant-service