version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant_db

  app:
    image: openjdk:11
    ports:
      - "8083:8083"
    volumes:
      - ./build/libs:/tenant-service
    command: ["java", "--enable-preview", "-jar", "/tenant-service/tenant-service-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db