version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant_db

  app:
    image: openjdk:11
    ports:
      - "8082:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/tenant_db
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    volumes:
      - ./build/libs:/tenant-service
    command: ["java", "--enable-preview", "-jar", "/tenant-service/tenant-service-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db