spring:
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true
---
# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:tenant_db}
spring:
  datasource:
    driver: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://${db.host}:${db.port}/${db.name}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    default-schema: metadata
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl : false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html

# ===============================
# JPA/ SCHEMA_TYPE
# ===============================
jpa:
  general_default_schema: speech4j
  metadata_default_schema: metadata

liquibase:
  general_changelog: db/changelog/db.changelog-tenant.yaml
  metadata_changelog: db/changelog/db.changelog-master.yaml

server:
  port: 8082
# ===============================
# TENANT/SPEECH4J
# ===============================
speech4j:
  email: ${SPEECH4j_EMAIL:speech4j@gmail.com}
  password: ${SPEECH4j_PASSWORD:super-secure-password}
  aws:
    accessKey: ${AWS_ACCESS_KEY:MAKIA2JLHKQCPETFM4J7D}
    secretKey: ${AWS_SECRET_KEY:ElIwuD+eUa0UXbkE9NZJlcbdBIWlwqNa8X+dHLJpM}
    bucketName: ${AWS_BUCKET_NAME:speech4j-content-bucket}
    endpointUrl: ${AWS_ENDPOINT_URL:https://speech4j-content-bucket.s3.us-east-2.amazonaws.com}
