spring:
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
---
# ===============================
# DATABASE
# ===============================
db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:tenant_db}
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    default-schema: metadata
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl : false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
# ===============================
# SWAGGER
# ===============================
#springdoc:
#  api-docs.ath: /api-docs
#  swagger-ui.path: /swagger-ui.html

# ===============================
# LIQUIBASE/CHANGELOG_TYPE
# ===============================
liquibase:
  general_changelog: db/changelog/db.changelog-tenant.yaml
  metadata_changelog: db/changelog/db.changelog-master.yaml

server:
  port: 8082
# ===============================
# TENANT/SPEECH4J
# ===============================
speech4j:
  email: ${SPEECH4j_EMAIL:speech4j@gmail.com}
  password: ${SPEECH4j_PASSWORD:super-secure-password}
  aws:
    accessKey: ${AWS_ACCESS_KEY:MAKIA2JLHKQCPETFM4J7D}
    secretKey: ${AWS_SECRET_KEY:ElIwuD+eUa0UXbkE9NZJlcbdBIWlwqNa8X+dHLJpM}
    bucketName: ${AWS_BUCKET_NAME:speech4j-content-bucket}
    endpointUrl: ${AWS_ENDPOINT_URL:https://speech4j-content-bucket.s3.us-east-2.amazonaws.com}

# ===============================
# LOGGER
# ===============================
logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.speech4j.tenantservice: DEBUG