spring.main.allow-bean-definition-overriding: true
# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
db:
  host: localhost
  port: 5432
  name: tenant_db
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}?currentSchema=speech4j
    username: postgres
    password: qwerty123
  liquibase:
    default-schema: metadata
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl : false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html

# ===============================
# JPA/ SCHEMA_TYPE
# ===============================
jpa:
  general_default_schema: speech4j
  metadata_default_schema: metadata