# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
db:
  host: db
  port: 5432
  name: tenant_db
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}?currentSchema=metadata
    username: postgres
    password: qwerty123
  liquibase:
    default-schema: metadata
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl : false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html
---
# ===============================
# SCHEMA-GENERATION / HIBERNATE
# ===============================
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: db/changelog/migrations/schema-script.sql