# ===============================
# Default connection pool
# ===============================
spring:
  datasource:
    hikari:
      connectionTimeout: 2000
      maximumPoolSize: 5
---
# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tenant_db?currentSchema=speech4j
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:qwerty123}
  liquibase:
    default-schema: speech4j
---
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa:show-sql: false
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
        generate_statistics: false
---
# ===============================
# SWAGGER
# ===============================
springdoc:
  api-docs.ath: /api-docs
  swagger-ui.path: /swagger-ui.html
---
# ===============================
# SCHEMA-GENERATION / HIBERNATE
# ===============================
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: db/changelog/migrations/schema-script.sql